module.exports = {
	cards: [],
	unShuffledCards: [],
	//create arrays for open cards and targetIDs
	openCards: [],
	targetIDs: [],
	//matchedCards array will contain all the matched cards used for error handling
	matchedCards: [],
	randomCards: [],
	randomCardTemp: [],
	randomDeck: [
		'fa-crow',
		'fa-dove',
		'fa-feather',
		'fa-frog',
		'fa-kiwi-bird',
		'fa-broadcast-tower',
		'fa-church',
		'fa-hospital',
		'fa-school',
		'fa-university',
		'fa-compass',
		'fa-dollar-sign',
		'fa-gift',
		'fa-heart',
		'fa-leaf',
		'fa-parachute-box',
		'fa-piggy-bank',
		'fa-seedling',
		'fa-poo',
		'fa-smile',
		'fa-frown',
		'fa-chess',
		'fa-chess-bishop',
		'fa-chess-king',
		'fa-chess-knight',
		'fa-chess-pawn',
		'fa-chess-queen',
		'fa-chess-rook',
		'fa-bug',
		'fa-coffee',
		'fa-keyboard',
		'fa-user-secret',
		'fa-microchip',
		'fa-money-bill-alt',
		'fa-bell',
		'fa-clock',
		'fa-hourglass-half',
		'fa-stopwatch',
		'fa-paint-brush',
		'fa-paper-plane',
		'fa-wrench',
		'fa-hand-spock',
		'fa-thumbs-up',
		'fa-ambulance',
		'fa-beer',
		'fa-home',
		'fa-anchor',
		'fa-bicycle',
		'fa-fighter-jet',
		'fa-bed',
		'fa-birthday-cake',
		'fa-bomb',
		'fa-blind',
		'fa-glass-martini',
		'fa-flag-checkered',
		'fa-eye',
		'fa-car',
		'fa-helicopter',
		'fa-gamepad',
		'fa-graduation-cap',
		'fa-motorcycle',
		'fa-paw',
		'fa-rocket',
		'fa-music',
		'fa-subway',
		'fa-binoculars',
		'fa-cube',
		'fa-dice',
		'fa-moon',
		'fa-snowflake',
		'fa-quidditch',
		'fa-futbol',
		'fa-football-ball',
		'fa-user-astronaut',
		'fa-user-ninja',
		'fa-bus'
	]
};
